# ==============================================================
# UAT / DEVELOPMENT PROFILE
# Active when: spring.profiles.active=uat  (default)
# ==============================================================

server:
  port: 7070
  tomcat:
    connection-timeout: 90000
    max-http-form-post-size: 200MB
    max-swallow-size: -1           # Unlimited: prevents EOFException when client aborts large uploads

spring:
  datasource:
    url: jdbc:postgresql://192.168.103.106:5432/account_online

# Oracle — full UAT config
oracle:
  dwh:
    datasource:
      jdbc-url: jdbc:oracle:thin:@//192.168.127.88:1521/stg
      username: stg
      password: Bnk$$444
      driver-class-name: oracle.jdbc.OracleDriver
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: Oracle-DWH-Pool
  stg:
    datasource:
      jdbc-url: jdbc:oracle:thin:@//192.168.127.88:1521/stg
      username: stg
      password: Bnk$$444
      driver-class-name: oracle.jdbc.OracleDriver
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: Oracle-STG-Pool
# Simulators — all disabled by default
simulator:
  report-logs: false
  aml:
    error: false
    high-risk: false
  camdx: false
  banking:
    camdx-error: false
    internal-error: false

cpb:
  environment: development
  camdx:
    url: http://192.168.103.106:8099/api/v1/
  aml:
    url: http://192.168.103.106:9095/api/aml
    username: cpbaml
    password: aml123!@#
  t24:
    url: http://192.168.127.31:7003
    username: L.HOURNG
    password: HOurng@2323
  mb:
    otpUrl: http://192.168.103.11:15004/CPBBank/services/CPBMobile?wsdl
    registerCodeUrl: http://192.168.103.13:8090/API/RegisterCustomerMB/
    secretKey: mobilebankingCPB@#%123
  otp:
    message: "Your OTP code for CPBank, Online Account Opening is:"

aml:
  dashboard:
    url: http://192.168.103.106:8282/aml-management?pageNo=1

jwt:
  expiration-min: 525600
  issuer: account-online-api

telegram:
  bot:
    token: "8227113200:AAGq1I7Hs0CjkSW99M9rgrIdlHpgM8r6NMY"
    uat-acl-chat-id: "-1002740302492"
    uat-monitor-chat-id: "-1003115792160"
    uat-dev-team-chat-id: "-1002740302492"
    compliance-mention: "@PHAT_MENGHOR"
    enabled: true
