package com.internal.feature.auth.security;

import com.internal.feature.logs_report.model.RequestLog;
import com.internal.feature.logs_report.service.RequestLogService;
import com.internal.feature.telegram_alerts.service.MonitoringService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import org.springframework.web.util.ContentCachingRequestWrapper;
import org.springframework.web.util.ContentCachingResponseWrapper;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

@Component
@Slf4j
@RequiredArgsConstructor
public class RequestLoggingFilter extends OncePerRequestFilter {

    private final RequestLogService requestLogService;
    private final MonitoringService monitoringService;

    @Value("${telegram.bot.uat-dev-team-chat-id:}")
    private String devTeamChatId;

    // Endpoints to exclude from logging (to reduce noise)
    private static final List<String> EXCLUDED_PATHS = Arrays.asList(
            "/swagger-ui",
            "/v3/api-docs",
            "/actuator",
            "/favicon.ico",
            "/webjars",
            "/api/images",
            "/api/v1/customer-images" // Added to fix UTF-8 error on image fetch
    );

    @Override
    protected void doFilterInternal(HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain) throws ServletException, IOException {

        // Skip logging for excluded paths
        String requestUri = request.getRequestURI();
        if (shouldSkipLogging(requestUri)) {
            filterChain.doFilter(request, response);
            return;
        }

        String apiKey = request.getHeader("X-API-KEY");

        long startTime = System.currentTimeMillis();
        ContentCachingRequestWrapper requestWrapper = new ContentCachingRequestWrapper(request);
        ContentCachingResponseWrapper responseWrapper = new ContentCachingResponseWrapper(response);

        Exception caughtException = null;

        try {
            filterChain.doFilter(requestWrapper, responseWrapper);
        } catch (Exception e) {
            caughtException = e;
            throw e;
        } finally {
            long duration = System.currentTimeMillis() - startTime;

            // Build and save request log to database
            RequestLog requestLog = buildRequestLog(requestWrapper, responseWrapper, apiKey, duration, caughtException);
            requestLogService.saveLog(requestLog);

            // Monitor: Log critical events
            if (requestLog.getIsSuccess() != null && !requestLog.getIsSuccess()) {
                // Failed request
                if (requestLog.getStatusCode() != null && requestLog.getStatusCode() >= 500) {
                    monitoringService.logExternalApiCall(
                            requestLog.getEndpoint(),
                            request.getMethod() + " " + request.getRequestURI(),
                            duration,
                            requestLog.getStatusCode(),
                            false);
                }
            }

            // Monitor: Detect suspicious authentication failures
            if (requestLog.getEndpoint() != null && requestLog.getEndpoint().contains("login")) {
                if (requestLog.getIsSuccess() != null && !requestLog.getIsSuccess()) {
                    String username = requestLog.getUsername() != null ? requestLog.getUsername() : "Unknown";
                    String ipAddress = requestLog.getIpAddress() != null ? requestLog.getIpAddress() : "Unknown";
                    monitoringService.logUserAuthentication(username, ipAddress, false);
                }
            }

            // Monitor: Performance alerts for slow requests
            if (duration > 5000) { // 5 second threshold
                monitoringService.logPerformanceAlert(
                        requestLog.getEndpoint(),
                        duration,
                        5000);
            }

            // Copy response body back
            responseWrapper.copyBodyToResponse();
        }
    }

    /**
     * Build RequestLog object from request data
     * Note: UUID is auto-generated by database, no need to set it manually
     */
    private RequestLog buildRequestLog(ContentCachingRequestWrapper request,
            ContentCachingResponseWrapper response,
            String apiKey,
            long duration,
            Exception exception) {

        String ipAddress = extractIpAddress(request);
        String username = extractUsername();
        String endpoint = truncate(request.getRequestURI(), 500);
        String method = request.getMethod();
        Integer statusCode = response.getStatus();
        String userAgent = truncate(request.getHeader("User-Agent"), 255);
        boolean isSuccess = (exception == null && statusCode >= 200 && statusCode < 400);
        String errorMessage = exception != null ? truncate(exception.getMessage(), 500) : null;

        String requestPayload = "";
        try {
            requestPayload = new String(request.getContentAsByteArray(), java.nio.charset.StandardCharsets.UTF_8);
            requestPayload = truncate(requestPayload, 10000);
        } catch (Exception e) {
            log.warn("Failed to parse request payload: {}", e.getMessage());
        }

        String responsePayload = "";
        String contentType = response.getContentType();
        if (contentType != null && (contentType.startsWith("image/") || contentType.startsWith("application/pdf")
                || contentType.startsWith("application/octet-stream"))) {
            responsePayload = "[Binary Content - " + contentType + "]";
        } else {
            try {
                responsePayload = new String(response.getContentAsByteArray(), java.nio.charset.StandardCharsets.UTF_8);
                responsePayload = truncate(responsePayload, 10000);
            } catch (Exception e) {
                log.warn("Failed to parse response payload: {}", e.getMessage());
            }
        }

        return RequestLog.builder()
                .requestPayload(requestPayload)
                .responsePayload(responsePayload)
                // id is auto-generated, don't set it
                .ipAddress(ipAddress)
                .username(username)
                .apiKey(apiKey)
                .endpoint(endpoint)
                .method(method)
                .statusCode(statusCode)
                .userAgent(userAgent)
                .durationMs(duration)
                .isSuccess(isSuccess)
                .errorMessage(errorMessage)
                .createdAt(LocalDateTime.now())
                .build();
    }

    /**
     * Extract IP address from request, handling proxies and load balancers
     */
    private String extractIpAddress(HttpServletRequest request) {
        String[] headerNames = {
                "X-Forwarded-For",
                "X-Real-IP",
                "Proxy-Client-IP",
                "WL-Proxy-Client-IP",
                "HTTP_X_FORWARDED_FOR",
                "HTTP_X_FORWARDED",
                "HTTP_X_CLUSTER_CLIENT_IP",
                "HTTP_CLIENT_IP",
                "HTTP_FORWARDED_FOR",
                "HTTP_FORWARDED"
        };

        for (String header : headerNames) {
            String ip = request.getHeader(header);
            if (ip != null && !ip.isEmpty() && !"unknown".equalsIgnoreCase(ip)) {
                // Take first IP if multiple are present
                if (ip.contains(",")) {
                    ip = ip.split(",")[0].trim();
                }
                return truncate(ip, 45);
            }
        }

        // Fallback to remote address
        String remoteAddr = request.getRemoteAddr();
        return truncate(remoteAddr != null ? remoteAddr : "unknown", 45);
    }

    /**
     * Extract username from security context
     */
    private String extractUsername() {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null && authentication.isAuthenticated()
                    && !"anonymousUser".equals(authentication.getPrincipal())) {
                String username = authentication.getName();
                return truncate(username, 100);
            }
        } catch (Exception e) {
            log.debug("Could not extract username: {}", e.getMessage());
        }
        return null;
    }

    /**
     * Check if path should be excluded from logging
     */
    private boolean shouldSkipLogging(String path) {
        return EXCLUDED_PATHS.stream().anyMatch(path::startsWith);
    }

    /**
     * Truncate string to maximum length to keep data small
     */
    private String truncate(String value, int maxLength) {
        if (value == null) {
            return null;
        }
        return value.length() > maxLength ? value.substring(0, maxLength) : value;
    }
}
